### ISSUE TITLE
How should the methods look like?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-flow-api#21]
@adioo How should the public interface looks like? Should the module export an object containing methods?

Should each method accept the app path as input? :thought_balloon:

**Comment by ottiker** [comment]
I think, creating an instance of the `flow-api` would be better. That way we can set the repo path via the `constructor`, which is used by the methods. But this depends how the API is used. Maybe thinking about how the builder would use the API would help.

**Comment by ottiker** [comment]
@gabipetrovay Maybe you have some input regarding an "app path" in containers?

**Comment by gabipetrovay** [comment]
The app will be mounted as a volume into the containers. It can look something like: `/app`. So you could hardcode it from my point of view. But I see the following options:
- `process.env.APP_PATH` or a global variable
- `/app` or similar hardcoding (not so good for non-container machines)
- (Adi) constructor with the app path passed (maybe optional and if not passed the `APP_PATH` environment variable will be checked)
- (Johnny) pass the path to each method (maybe also optional, using some defaults if not provided)

Now, the context where this module will be used. If used inside service, you can not hardcode the path or assume only one location because you are handling many applications.

I don't find Johnny proposal bad, because that would allow us to use the same module in service (providing a path) but also inside the application runtime (using the defaults).

**Comment by IonicaBizau** [comment]
> I don't find Johnny proposal bad, because that would allow us to use the same module in service (providing a path) but also inside the application runtime (using the defaults).

@gabipetrovay I am for using instances, because that way we can cache some things on the server side (e.g. read the composition once and then edit it in-memory). :balloon:

**Comment by ottiker** [comment]
@gabipetrovay @IonicaBizau 
We should make a session about this topic and discuss in general how we want to build API's. And what are the different environments, they need to run in (ex. Service App, Engine, Terminal Container?, etc).

**Comment by gabipetrovay** [comment]
Almost anytime good for me today. Tomorrow afternoon only.

**Comment by gabipetrovay** [comment]
An idea how to cache flow-api instance:

``` js
var app_flow_api_instances = {
    appId1: { ... }, // flow-api instance 1
    appId2: { ... }, // flow-api instance 2
    appId3: { ... } // flow-api instance 3
}
```

An idea how to handle flow-api instances:

``` js
exports.aServiceApiMethod = function (data) {
    // get a grip on the correct app ID
    var appId = ...;
    // try to get the flow-api instance form the cache
    var appFlowApi = app_flow_api_instances[appId];
    if (!appFlowApi) {
        // create and cache a new flow-api instance for this app
        appFlowApi = app_flow_api_instances[appId] = createFlowApiInstance(appId, "pubsub");
    }

    appFlowApi.method(data);
}
```

An idea how to create flow-api instances:

``` js
function createFlowApiInstance(appId, type) {
    // create a flow-api adapter (fs, pubsub, etc.)
    var adapter;
    // based on the type, we can have different types of adapter (a switch?)
    ...

    return adapter;
}
```

**Comment by ottiker** [comment]
**Session results:**
- Use factory pattern for flow-api `flowApi(/*adapter instance*/)`
- Create adapter for every `terminal-container` (this is a Builder or Service job).
- Simple FS `CRUD` adapter for local development.
